RoadName/Models/Roadname.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RoadName.Models
{
    public enum District
    {
        Ampara,
        Anuradhapura,
        Badulla,
        Batticaloa,
        Colombo,
        Galle,
        Gampaha,
        Hambantota,
        Jaffna,
        Kalutara,
        Kandy,
        Kegalle,
        Kilinochchi,
        Kurunegala,
        Mannar,
        Matale,
        Matara,
        Moneragala,
        Mullaitivu,
        [Display(Name = "Nuwara Eliya")]
        NuwaraEliya,
        Polonnaruwa,
        Puttalam,
        Ratnapura,
        Trincomalee,
        Vavuniya
    }
    public class Roadname
    {
        public int Id { get; set; }

        [DisplayName("Your Account ID")]
        public string ApplicationUserId { get; set; }

        [Required]
        [Display(Name =" Name Of the Road (Ex: Queen's Road)")]
        public string NameOfRoad { get; set; }

        [Required]
        [Display(Name = "District")]
        public District District { get; set; }

        [Required]
        [Display(Name = "City")]
        public string City { get; set; }
        [Required]
        [Display(Name = "Loaction")]
        public string Location { get; set; }

        [Display(Name = "Fill the Famouse People's Name(Ex : Minister, Writers, Sportments, Actors..etc)")]
        public string VIPName { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Based Story of Road")]
        public string Story { get; set; }

        public virtual ApplicationUser user { get; set; }
    }
}

RoadName/Controllers/RoadnameController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RoadName.Models;
using Microsoft.AspNet.Identity;

namespace RoadName.Controllers
{
    public class RoadnameController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Roadname
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var roadNames = db.Roadnames.Where(w => w.ApplicationUserId == userId);
            //var roadnames = db.Roadnames.Include(r => r.user);
            return View(roadNames.ToList());
        }

        // GET: Roadname/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roadname roadname = db.Roadnames.Find(id);
            if (roadname == null)
            {
                return HttpNotFound();
            }
            return View(roadname);
        }

        // GET: Roadname/Create
        public ActionResult Create()
        {
            var UserId = User.Identity.GetUserId();
            var CurrentUserID = db.Users.Where(e => e.Id == UserId);
            ViewBag.ApplicationUserId = new SelectList(CurrentUserID, "Id", "FirstName");
            return View();
        }

        // POST: Roadname/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ApplicationUserId,NameOfRoad,District,City,Location,VIPName,Story")] Roadname roadname)
        {
            if (ModelState.IsValid)
            {
                db.Roadnames.Add(roadname);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var UserId = User.Identity.GetUserId();
            var CurrentUserID = db.Users.Where(e => e.Id == UserId);
            ViewBag.ApplicationUserId = new SelectList(CurrentUserID, "Id", "FirstName", roadname.ApplicationUserId);
            return View(roadname);
        }

        // GET: Roadname/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roadname roadname = db.Roadnames.Find(id);
            if (roadname == null)
            {
                return HttpNotFound();
            }

            var UserId = User.Identity.GetUserId();
            var CurrentUserID = db.Users.Where(e => e.Id == UserId);
            ViewBag.ApplicationUserId = new SelectList(CurrentUserID, "Id", "FirstName", roadname.ApplicationUserId);
            return View(roadname);
        }

        // POST: Roadname/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ApplicationUserId,NameOfRoad,District,City,Location,VIPName,Story")] Roadname roadname)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roadname).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var UserId = User.Identity.GetUserId();
            var CurrentUserID = db.Users.Where(e => e.Id == UserId);
            ViewBag.ApplicationUserId = new SelectList(CurrentUserID, "Id", "FirstName", roadname.ApplicationUserId);
            return View(roadname);
        }

        // GET: Roadname/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roadname roadname = db.Roadnames.Find(id);
            if (roadname == null)
            {
                return HttpNotFound();
            }
            return View(roadname);
        }

        // POST: Roadname/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Roadname roadname = db.Roadnames.Find(id);
            db.Roadnames.Remove(roadname);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RoadName/Controllers/UserHomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RoadName.Controllers
{
    public class UserHomePageController : Controller
    {
        // GET: UserHomePage
        public ActionResult Index()
        {
            return View();
        }
    }
}

RoadName/Views/Roadname/Create.cshtml
@model RoadName.Models.Roadname

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Roadname</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.ApplicationUserId, "ApplicationUserId", htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="col-md-10">
                        @Html.DropDownList("ApplicationUserId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NameOfRoad, htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NameOfRoad, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NameOfRoad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.District, htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.District, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.VIPName, htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.VIPName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.VIPName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Story, htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Story, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Story, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Home", "Index", "UserHomePage")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RoadName/Views/Roadname/Delete.cshtml
@model RoadName.Models.Roadname

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Roadname</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.user.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameOfRoad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameOfRoad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.District)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.District)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VIPName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VIPName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Story)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Story)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RoadName/Views/Roadname/Details.cshtml
@model RoadName.Models.Roadname

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Roadname</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.user.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameOfRoad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameOfRoad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.District)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.District)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VIPName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VIPName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Story)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Story)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RoadName/Views/Roadname/Edit.cshtml
@model RoadName.Models.Roadname

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Roadname</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationUserId, "ApplicationUserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApplicationUserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameOfRoad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameOfRoad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameOfRoad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.District, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.District, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VIPName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VIPName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VIPName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Story, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Story, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Story, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RoadName/Views/Roadname/Index.cshtml
@model IEnumerable<RoadName.Models.Roadname>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.user.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameOfRoad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.District)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VIPName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Story)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.user.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NameOfRoad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.District)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VIPName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Story)
        </td>
        <td>
            
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id}) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id})
            
            
        </td>
    </tr>
}

</table>